[package]
name = "axum-auth"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.4"
serde_json = "1.0.140"
tokio = { version = "1.44.2", features = ["full"] }
jwt-lib = { path = "../jwt-lib" }
async-trait = "0.1.88"
